### ISSUE TITLE
Instructions 

### ISSUE THREAD

**Issue by mosn** [magicspon/gatsby-starter-craftcms-storybook#1]
If possibe please provide instruction as to how to install this. I can also refer to [Gatsby-craftcms](https://github.com/magicspon/gatsby-starter-craftcms) starter post if they're identical;

**Comment by magicspon** [comment]
@mosn I've added some docs to the README.md

https://github.com/magicspon/gatsby-starter-craftcms-storybook/blob/master/README.md

Let me know if you have any other questions.
